### ISSUE TITLE
Feature request: configuration to not check certain modules/files with mypy

### ISSUE THREAD

**Issue by MrGreenTea** [python-lsp/pylsp-mypy#67]
For example I don't want my `test_` files littered with `mypy` diagnostics.
For this reason my `pyproject.toml` looks something like this:
```toml
# pyproject.toml
[tool.mypy]
exclude = ["tests", 'test_.+\.py']
```

I propose to include this configuration option somehow and not run `mypy` on files that match a regex inside `exclude`. But I am open to other options as well if they make more sense or are easier to implement :)
